[package]
name = "grep_lite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
data-encoding = "2.4.0"
error-chain = "0.12.4"
regex = "^1"
ring = "0.17.5"
